apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: server
        image: myapp-server
        env:
          - name: DATABASE
            value: "test"
          - name: SECRET
            value: "AartiProduction"
          - name: PORT
            value: "8000"
          - name: MONGO_USER
            value: "harishsugandhi09"
          - name: MONGO_PASSWORD
            value: "a1haOGDOIBEdkU8c"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: myapp-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
